<a href="https://colab.research.google.com/github/Woongstar/AItrack/blob/main/%EC%95%84%EC%9D%B4%EB%A6%AC%EC%8A%A4%ED%92%88%EC%A2%85%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import pandas as pd

In [3]:
path = '/content/drive/MyDrive/인공지능트랙/코딩야학/csv/iris.csv'
iris = pd.read_csv(path)

In [4]:
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [6]:
#Onehot-encoding
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [7]:
print(encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [9]:
#독립변변수 종속변수 분리
독립 = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = encoding[['품종_virginica', '품종_setosa', '품종_versicolor']]
print(독립.shape,종속.shape)

(150, 4) (150, 3)


In [12]:
x= tf.keras.layers.Input(shape=[4])
y= tf.keras.layers.Dense(3,activation='softmax')(x)
model = tf.keras.models.Model(x,y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [22]:
#fit
model.fit(독립,종속,epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1582 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1575 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1573 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1571 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1574 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1571 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1574 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1565 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1568 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1564 - accuracy: 0.9733


In [29]:
print(model.predict(독립[:5]))

[[9.7730464e-08 9.9905032e-01 9.4953901e-04]
 [7.8400899e-07 9.9610341e-01 3.8958187e-03]
 [3.2045054e-07 9.9828869e-01 1.7108798e-03]
 [1.4320316e-06 9.9527490e-01 4.7237044e-03]
 [7.9964501e-08 9.9924821e-01 7.5166934e-04]]


In [30]:
print(종속[:5])

   품종_virginica  품종_setosa  품종_versicolor
0             0          1              0
1             0          1              0
2             0          1              0
3             0          1              0
4             0          1              0


In [31]:
model.get_weights()

[array([[-0.2035927 ,  1.3407215 ,  0.99037087],
        [-1.1836286 ,  2.3689685 , -0.32016194],
        [ 1.097436  , -3.854827  , -0.28153017],
        [ 1.4270021 , -4.121436  , -2.1708357 ]], dtype=float32),
 array([-1.7405009,  2.1323657,  0.9797909], dtype=float32)]